spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentdb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false&verifyServerCertificate=false
    username: test
    password: rxCv3rPw#
    hikari:
     maximum-pool-size: 5
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        enable_lazy_load_no_trans: true
  data:
    elasticsearch:
      cluster-nodes: 192.61.71.226:9300
      cluster-name: local-elastic-cluster
      repositories:
        enabled: true
server:
  port: 8084
