spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.61.236:3306/masterdb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false&verifyServerCertificate=false
    username: gatidev
    password: rxv3rPw#
    hikari:
     maximum-pool-size: 5
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        enable_lazy_load_no_trans: true
  data:
    elasticsearch:
      cluster-nodes: 172.31.61.236:9300
      cluster-name: gati-elastic-cluster
      repositories:
        enabled: true
server:
  port: 8084